name: build-deb-action
  # You may pin to the exact commit or the version.
  # uses: jiro4989/build-deb-action@59ff85390fe87391c9d7b24aa764d7d10d9a81c9
  uses: jiro4989/build-deb-action@v2.1.0
  with:
    # Working directory relative to the root directory.
    package: cutefish-wallpapers  
    # Working directory relative to the root directory.
    package_root: .debpkg
    # Report level for reviewdog [info,warning,error]
    maintainer: Maksym Titenko
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
    version: 0.3-1
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    arch: amd64
    # description
